### ISSUE TITLE
Display Popup On Change

### ISSUE THREAD

**Issue by mbechto** [frederikb/bookmarksync#13]
Display the "Bookmarks have been updated" popup only when the bookmarks actually have changed.

**Comment by frederikb** [comment]
@mbechto Thanks for the suggestion. I agree that this would be better UX. 

Unfortunately the update mechanism is currently very simple - we just replace the bookmark trees entirely instead of performing some kind of diff. This avoids a potentially buggy diff/merge and is fast enough so far.

I'll take another look and see if there is a simple alternative to detect differences for this purpose.

**Comment by mbechto** [comment]
Maybe it would be possible to save the git commit hash somewhere and compare that?

**Comment by frederikb** [comment]
@mbechto  Good suggestion and feasible, thanks.

I will implement that and consequently increase the update frequency a bit since now the popups will only appear if necessary.

The manual sync button is already designed to force a sync and should therefore bypass the revision check. This should help sort out accidental changes done to these bookmarks by the user.

**Comment by frederikb** [comment]
I remembered that I was already using ETags received from the GitHub REST API and caching them in order to prevent uneccessary updates to the bookmarks in case the source (file or directory) was unchanged.

Unfortunately this didn't work because the cached ETag was lost between bookmark syncs. The synchronization happens event-driven inside of a so-called background script. These are unloaded after a period of idle time by the browser, thus losing any state saved.

I fixed this in #40 and consequently increased the bookmark sync frequency to hourly in #41.
