### ISSUE TITLE
I am a new user, this is not syncing my existing Bookmarks

### ISSUE THREAD

**Issue by nomandhoni-cs** [frederikb/bookmarksync#90]

**Comment by frederikb** [comment]
Hi @nomandhoni-cs,

Thanks for trying out my extension and I'm happy to help you out! Unfortunately your issue is lacking some detail. Could you please expand on:

- What your intent is / what you are attempting to accomplish
- Your current configuration of the extension
- The observed problem

Thanks!

**Comment by frederikb** [comment]
Closing due to lack of feedback. Feel free to re-open with additional information. 

I hope you managed to get it working in the meantime.
